# Generated by Django 2.1.3 on 2019-01-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='titlw',
            new_name='title',
        ),
    ]
