# Generated by Django 2.1.3 on 2018-12-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181203_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
